"use strict";
export const __esModule = true;
export const WHITE = "white";
export const BRIGHT_BLUE = "var(--Bright-Blue)";
export const VERY_LIGHT_GRAY = "var(--Very-Light-Gray)";
export const VERY_LIGHT_GRAYISH_BLUE = "var(--Very-Light-Grayish-Blue)";
export const LIGHT_GRAYISH_BLUE_LT = "var(--Light-Grayish-Blue-lt)";
export const DARK_GRAYISH_BLUE_LT = "var(--Dark-Grayish-Blue-lt)";
export const VERY_DARK_GRAYISH_BLUE_LT = "var(--Very-Dark-Grayish-Blue-lt)";
export const VERY_DARK_BLUE = "var(--Very-Dark-Blue)";
export const VERY_DARK_DESATURATED_BLUE = "var(--Very-Dark-Desaturated-Blue)";
export const LIGHT_GRAYISH_BLUE = "var(--Light-Grayish-Blue)";
export const LIGHT_GRAYISH_BLUE_HOVER = "var(--Light-Grayish-Blue-hover)";
export const DARK_GRAYISH_BLUE = "var(--Dark-Grayish-Blue)";
export const VERY_DARK_GRAYISH_BLUE_DT = "var(--Very-Dark-Grayish-Blue-dt)";
export const VERY_DARK_GRAYISH_BLUE = "var(--Very-Dark-Grayish-Blue)";
